source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SamplePodTest_Example', :exclusive => true do
  pod 'SamplePodTest', :path => '../'
end

target 'SamplePodTest_Tests', :exclusive => true do
  pod 'SamplePodTest', :path => '../'

  
end
